language: node_js
cache:
  directories:
  - node_modules
node_js: stable
branches:
  only:
  - master
install:
- npm config set registry https://registry.npm.taobao.org
- npm install
scripts:
- npm run build:prod
addons:
  ssh_known_hosts: 47.98.183.206
after_success:
- chmod 600 ~/.ssh/id_rsa
- sshpass -p $DEPLOY_PASS scp -o stricthostkeychecking=no -r ./dist/* root@47.98.183.206:/usr/share/nginx/html
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
env:
  global:
    secure: sgG/oUjlY/eOSife9dRxBIvphuf4Udpd/LBLE2MA0EgNPkiPJIHkjakIIWaM+fGWk31DfTL6R4mOTfCvSUn3nbDM6X7UZArReny+sFcORGWVlGRuoRjKKR/jXL1bGCgwD9/V1agOdGMeQ/BZB50nmDTvzK/c4jRHBS9RNs4JLR7b37Cl3SeC2ZpiSSDYnYVZIRtIDikQv9oRl7xTUM8h2Ku+CKMvpFX0dOADI/SjS41C3Wp93+14dVdYst8GUP5XfN9g+qyg62rSFDFmA0VWICdFgiHFr9d8pTizdyTuPElYym/M91ry63PbvvLsevf4B4hzI1JVoKBHllVmWKgv+1/U2zptu/Gxqh3hUt8XFLswZwKP4IooOM0NkmMT/fd1KiXQxThQOAcplVGG4D9TBqHEjkOmSoObjnEC1EhBC3Ppuz6GsHh7kVRd3GRDAO5y7GOqmDUH/DNNHVbqKXVeCX2HIQfe2E1SvkwDF1wUCtmb+Qgrp4C360OXME77KIstO+y+cAe0OVMAdDRyvSSrhs/S+Id0bY2qjF8zVX2QuUkVk3po/7x0Fgwj1Vv/ln/9ZECp94eGYHAZpeK0AZf0tujxTj6U0Xrs/UOLJHbraOlOlluUfYepGumH5wC8aExRa1u1WUgEZeIRCFJ4W4JqINiALeW7HVDvpr8Q3EPTfUA=
