language: node_js
cache:
  directories:
  - node_modules
node_js: stable
branches:
  only:
  - master
install:
- npm install
scripts:
- npm run build:prod
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
