language: node_js
cache:
  directories:
  - node_modules
node_js: stable
branches:
  only:
  - master
install:
- npm config set registry https://registry.npm.taobao.org
- npm install
scripts:
- npm run build:prod
addons:
  ssh_known_hosts: 47.98.183.206
after_success:
- scp -o stricthostkeychecking=no -r ./dist/* root@47.98.183.206:/usr/share/nginx/html
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
