language: node_js
cache:
  directories:
  - node_modules
node_js:
- 12.19.0
branches:
  only:
  - master
install:
- npm config set registry https://registry.npm.taobao.org
- npm install
scripts:
- npm run build:prod
addons:
  ssh_known_hosts: 47.98.183.206
  apt:
    packages:
    - sshpass
after_success:
- chmod 600 ~/.ssh/id_rsa
- export SSHPASS=$DEPLOY_PASS
- sshpass -e ssh -o stricthostkeychecking=no root@47.98.183.206 "cd /eric/personal-web/personal-web-admin
  && git pull origin master && export PATH=/usr/local/node/12.19.0/bin:$PATH && sh
  ./deploy.sh"
env:
  global:
  - secure: k/8A7zZrLja/BjfrH/TffXLdhShvVyVeQLO3P5Yk9TIzH6PR8FSAgSKFSNEAP87VxdZLWzMV2Ub3OvkcZeApKVmoNqN+c/QHMs7s5y4U32doNmDXm0lHqEpq7nGDoM1fAsDM/HGDPT4TXUn8lh27Ia3YhBVSJtAx9JiLySAeR+vq42W7phGXXuxIVuXo6QRYxN5PoYSzVfZzYZ7OWJX+UEfaLSUxb5PNpYaXBvHSs/Mtqgmy2xqSii6lLJa+YuFJ2ZXSW36EIkgWVEJ6ZVG8y2haZCdHD5In0S9XdNlhOp/vcxIuNzC/gWEVhqZfO6xZwtTgwKqMRlc3OIj+boYK/pgU/fnaXaawBRpayZYjF5d4YeyXM7WEdJiczKDPbqmpQ+JSAewg92AA3CIj4XSHamc6ifg/XC/hKizQsLq9/z7kwEPzN+1eC7QXWc2blNqVUtLP0l9kj+w8+W0WJ845iszDx8ciWtiUgSxOGmAYqvAmxwh2KiPsEjxzZbsIvw6BiJjY/bjbOk/cUrIYgEpqwXfLthxoln9V8XTYZTCuzDc+pmn2RNCU6360VjBx+KODD/BJck6Fqz3TPIiolaaAiX+njrFEr5ZlSdhUVUrNbkeOMbjl3oZ0T21QCAlECeBKhLRgBfqG2UaPqd2A37ffMKPmlpyYbVr1uhmGYjNc+tc=
